"""Assemble verbatim generated scripts into labeled, ordered notebook cells."""
from pathlib import Path
import nbformat

ROOT = Path(__file__).resolve().parent
intro = """# Building an Image Classifier with PyTorch — ChatGPT/Codex

**Assignment:** regenerate the image-classification workflow from the previous session, including training-accuracy plots, and submit a newly executed notebook and its HTML rendering.

This notebook was freshly assembled and executed on September 25, 2026, using the seven generated scripts from the earlier session.

**Reference:** Aurélien Géron, *Hands-On Machine Learning with Scikit-Learn and PyTorch* (2025), Chapter 10, “Building an Image Classifier with PyTorch,” cells 111–132 of the supplied `10_neural_nets_with_pytorch.ipynb`. The reference's `train2` helper and 20-epoch setting occur earlier in that notebook. This is a self-contained adaptation generated by OpenAI Codex; it does not claim to be a Claude run.

## Run instructions
Use Python 3.12 with the supplied pinned requirements (the reference requires Python 3.10 or newer). Install `requirements.txt` in your environment, select that environment as the notebook kernel, and run all cells from top to bottom with this folder as your working directory. The first run downloads Fashion-MNIST to `datasets/`; generated metrics, plots and weights are saved in `artifacts/`. Installation is a prerequisite, not a hidden notebook step.

## Method and scope
Fashion-MNIST contains 60,000 training and 10,000 test grayscale images of size 28 × 28. We split the training pool into 55,000 training and 5,000 validation examples with seed 42. The network is Flatten → Linear(784, 300) → ReLU → Linear(300, 100) → ReLU → Linear(100, 10), trained with cross-entropy and SGD, learning rate 0.1, batch size 32, for 20 epochs. These choices follow the supplied reference.

Added features include per-epoch accuracy and loss plots, sample-weighted metrics, validation-based checkpoint selection, held-out test evaluation, saved results, and a save/reload check. Accuracy is computed directly as correct predictions divided by sample count, without an extra TorchMetrics dependency. Training accuracy measures predictions during parameter updates; validation accuracy measures the model after each epoch. They are not measured at exactly the same model state. Test data is not used for checkpoint selection. We use CPU with deterministic operations; results can still vary across software versions and hardware.

## Script-to-cell mapping
Each numbered stage below contains the **exact source** of its matching `scripts/NN_*.py` file. The seven stage files share state and must execute in order; `run_all.py` runs them together outside Jupyter. `build_notebook.py` assembles this notebook and `execute_notebook.py` executes it and exports HTML; these tooling scripts are not classifier cells.
"""
descriptions = [
    ("Setup and reproducibility", "Imports, explicit configuration and output directories."),
    ("Dataset and inspection", "Download and scale images to [0, 1], split the training pool, create loaders, and inspect examples."),
    ("Classifier", "Define the reference MLP and check its output shape and 266,610 trainable parameters. CrossEntropyLoss accepts logits, so no softmax is applied before training loss."),
    ("Training and validation", "Train for 20 epochs and retain the model with the highest validation accuracy. Loss is weighted by batch size, including the final partial batch."),
    ("Accuracy and loss plots", "Plot both training and validation accuracy by epoch, alongside cross-entropy loss. This is the requested extension."),
    ("Test evaluation and predictions", "Evaluate the selected model once on the test set, inspect predictions, and save metrics. Top-four probabilities are selected from the full ten-class softmax; they are not renormalized."),
    ("Save and reload verification", "Save model weights, instantiate a fresh model, and check that its logits match the original model.")]
cells = [nbformat.v4.new_markdown_cell(intro)]
for stage, (path, (title, description)) in enumerate(zip(sorted((ROOT / "scripts").glob("[0-9][0-9]_*.py")), descriptions), 1):
    cells.append(nbformat.v4.new_markdown_cell(
        f"## Stage {stage} / code cell {stage}: {title}\n\n**Generated script:** `scripts/{path.name}`\n\n{description}"))
    cells.append(nbformat.v4.new_code_cell(path.read_text(), metadata={"source_script": f"scripts/{path.name}"}))
cells.append(nbformat.v4.new_markdown_cell("""## Interpretation and limitations
The printed metrics and embedded figures above are outputs from the executed code. Increasing training accuracy with stagnant or falling validation accuracy suggests overfitting. Validation-based selection mitigates selecting a worse final epoch, but does not establish generalization beyond this dataset. This is one seeded run of a simple fully connected baseline, not an architecture comparison or evidence of a difference between Claude and OpenAI. Results are printed above and saved to `artifacts/results.json` when the notebook runs.
"""))
nb = nbformat.v4.new_notebook(cells=cells, metadata={"kernelspec": {"name": "python3", "display_name": "Python 3", "language": "python"}})
nbformat.write(nb, ROOT / "image_classifier.ipynb")
print("Built image_classifier.ipynb with seven labeled code cells.")
